name = "JosephsonSTA"
uuid = "0f57ff0d-e87d-46e3-b1bb-275a51971cfa"
authors = ["manuel <manuel.odelli@gmail.com> and contributors"]
version = "0.1.0"

[deps]
HCubature = "19dc6840-f33b-545b-b366-655c7e3ffd49"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
SpecialPolynomials = "a25cea48-d430-424a-8ee7-0d3ad3742e9e"

[compat]
QuadGK = "2"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
